### ISSUE TITLE
gitlab 版本升级

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/perf-test#14]

**Comment by Xuntian** [comment]
https://keepwork.com/wiki/wikieditor/#/lizq/keepwork_devops/gitlab

**Comment by Xuntian** [comment]
升级测试已在stage环境上实现，stage环境的gitlab版本已经升至11.3.4

**Comment by Xuntian** [comment]
release环境的gitlab的服务已成功升级至11.3.4
