### ISSUE TITLE
运维环境区分

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/perf-test#16]
@LiXizhi commented on [Thu Oct 18 2018](https://github.com/tatfook/keepwork/issues/2520)

**Comment by leopoldchen** [comment]
目前dev环境、release环境和prod环境共享keepwork域名。
除了直接导致cookie冲突问题，对CICD也会有影响，会导致某些域名不能使用。

**Comment by Xuntian** [comment]
暂时仅用dev.lizq.top和rls.lizq.top俩个域名区分开发和测试环境

**Comment by Xuntian** [comment]
目前在规划新建一个线上环境的k8s集群，现有集群作为测试使用，将环境完全区分开

**Comment by Xuntian** [comment]
keepwork正式环境已经迁移至新的k8s集群

**Comment by ysj15** [comment]
DNS可以解决测试与生产域名分开问题

**Comment by Xuntian** [comment]
测试和生产环境完全区分 下一步要修改配置和域名，以及nginx配置

**Comment by Xuntian** [comment]
已经将dev、rls环境和正式环境分离开，dev环境使用*dev.kp-para.cn域名，rls使用*rls.kp-para.cn域名
