### ISSUE TITLE
paraworld-ci

### ISSUE THREAD

**Issue by Xuntian** [tatfook/perf-test#19]

**Comment by Xuntian** [comment]
https://keepwork.com/lizq/paraword/para-ci/updater

**Comment by Xuntian** [comment]
1, p4d server depot issue
2, P4DAssetServer， 已经部署，需要与nginx对接
3, jenkins ci

**Comment by Xuntian** [comment]
各个环节已经联通，这周交由张磊那边测试

**Comment by LiXizhi** [comment]
good.
