### ISSUE TITLE
Paracraft 移动APP发布

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/perf-test#21]
现在需要将我们的AndroidAPP以大富网络的名义，发到国内外的主流平台上。 
PC版外加发到Steam.  ICP和文网文证书可以问冯冯要. 

- 手机渠道:  应用宝， 华为应用商店， google app store 等
- PC渠道：Steam，等

**Comment by Xuntian** [comment]
@LiXizhi 华为app商城去年已经发布过了，需要找到之前的账号，我这边的可能需要注销

**Comment by Xuntian** [comment]
华为app商店已经成功发布了

**Comment by LiXizhi** [comment]
好的， 其它的也继续发布， 首次审核比较难， 更新比较容易。

**Comment by ouyc** [comment]
已转至paracraft board  issue 51
