### ISSUE TITLE
新版支付对接测试

### ISSUE THREAD

**Issue by LiXizhi** [tatfook/perf-test#25]
### Background

哈奇server是通过信任ip的形式来处理支付的回调的，因此在我们做了服务迁移之后，可能需要更新ip。

### Issue

目前计划将支付服务部署在docker中，那么就会面临ip不稳定的问题。因此，需要尽快验证可用性，以保证支付服务可以正常上线。

**Comment by Xuntian** [comment]
添加认证IP的方案已经测试可以生效
