### ISSUE TITLE
新搭建线上环境k8s集群

### ISSUE THREAD

**Issue by ouyc** [tatfook/perf-test#26]
@Xuntian commented on [Wed Apr 10 2019](https://github.com/tatfook/keepwork/issues/4151)

**Comment by Xuntian** [comment]
线上环境k8s集群，harbor仓库已经搭建好，下一步联调jenkins

**Comment by Xuntian** [comment]
目前存在问题：harbor仓库连接不上

**Comment by Xuntian** [comment]
harbor仓库问题已解决
