### ISSUE TITLE
优化keepwork项目构建流程

### ISSUE THREAD

**Issue by ouyc** [tatfook/perf-test#27]
@Xuntian commented on [Wed Apr 10 2019](https://github.com/tatfook/keepwork/issues/4152)

---

@Xuntian commented on [Mon Apr 15 2019](https://github.com/tatfook/keepwork/issues/4152#issuecomment-483152636)

之后将构建流程迁移至虚拟机，利用缓存优化构建过程

**Comment by Xuntian** [comment]
新建k8s集群的项目构建流程已按照方案优化完成
