### ISSUE TITLE
k8s环境搭建

### ISSUE THREAD

**Issue by leopoldchen** [tatfook/perf-test#3]
### 目标

搭建k8s服务，并逐步将测试和生产环境迁移过去

**Comment by Xuntian** [comment]
已在内网实体机上部署3个节点的kubernetes集群，一个master，俩个node节点，内部dns，dashboard, ingress controller, 节点监控的heapster已经可以正常使用，harbor仓库，用于cicd的jenkins和集群日志efk还没搞定

**Comment by Xuntian** [comment]
已经基本完成，下一步整理文档和k8s的使用测试
